### ISSUE TITLE
connect to noflo ui

### ISSUE THREAD

**Issue by stvogel** [noflo/noflo-runtime-msgflo#201]
Maybe I'm just to stupid to use this, I have rabbitmq installed and msgflo.
I started noflo-runtime-msgflo successfully (at least it tells me "started ..."

How do I now connect my local msgflo-runtime in the (also locally running) noflo-ui?
I tried to add a manual runtime and specified "msgflo" as the type.

But noflo-ui always tells me "Runtime not available".

Thanks for any hints

**Comment by bergie** [comment]
NoFlo runtime for MsgFlo doesn't provide a runtime endpoint. For editing the NoFlo graph you can use noflo-nodejs, and for editing the MsgFlo graph you can run the `msgflo` command

**Comment by bergie** [comment]
Setup example https://github.com/flowhub/powertechnician/blob/master/package.json#L9

**Comment by stvogel** [comment]
Hi bergie,
thanks for the quick reply and your help.
This is all quite confusing.
According to your package.json I can now connect to the msgflo-runtime. Yeah :-)

Ok ... but now a myriad of other question arise ... but well I have to dig through some of the spare resources that are there.
The docs are a real pita.
This could be such a great way to do things, but it's quite frustrating to get it up and running.

**Comment by bergie** [comment]
Yep, that's the downside of making tools for ourselves first. I hope we'll be able to put some effort in proper getting started documentation and some prepared Docker containers soon. @uwekamper said he'd like to help with that

**Comment by jonnor** [comment]
Good that you managed to get Flowhub connected to your MsgFlo runtime.
Do file issues for other problems you run into, or other questions you may have!

FYI: There now also exists a MsgFlo project template, based on Docker, here: https://github.com/noflo/noflo-runtime-msgflo/issues/201
