### ISSUE TITLE
IP object and scope support

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-runtime-msgflo#54]
The next major NoFlo release will add support for scopeable IP objects. This would enable easier process isolation per message.

See:

* noflo/noflo#162
* noflo/noflo#356

**Comment by jonnor** [comment]
If noflo has a property which we can feature detect this on, then we'll send an IP with `scope: foo` instead of the `begingroup foo`, `data`, `endgroup foo`.

**Comment by jonnor** [comment]
Duplicate of #68
